### ISSUE TITLE
FlutterError (Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by Smyczek** [bxqm/material_floating_search_bar#72] opened 2022-01-08 00:52 UTC
Hello,
I copied example 1:1 and when I don't write anything in the search bar and try to back to normal view (using back button or backdrop tap) Flutter throw this exception:
_____________________________________________________________
Exception has occurred.
FlutterError (Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.)
_____________________________________________________________

![error](https://user-images.githubusercontent.com/3749053/148646309-5717e4dd-3c4f-456d-be92-a8c8c99bbd10.gif)

The only one change vs. example is environment I use (latest) sdk: ">=2.16.0-80.1.beta <3.0.0"

When I write something then it works ok. Any idea how to solve this issue?

**Comment by ruro-ken** [comment] 2022-02-04 07:20
Hi,
Exactly the same error here. maybe after flutter upgrade? I'm not sure.

**Comment by SungilJung** [comment] 2022-02-04 09:53
If I fix it like this, it works fine.

```diff
 abstract class ImplicitlyAnimatedWidgetState<T,
         W extends ImplicitlyAnimatedWidget> extends State<W>
     with TickerProviderStateMixin {
-  late final _controller = AnimationController(
-    duration: widget.duration,
-    vsync: this,
-  )
-    ..value = 1.0
-    ..addListener(
-      () => setState(
-        () => value = lerp(oldValue, newValue, _animation.value),
-      ),
-    );
-
-  late var _animation = CurvedAnimation(
-    curve: widget.curve,
-    parent: _controller,
-  );
+  late final AnimationController _controller;
+  late final CurvedAnimation _animation;

   T get newValue;
   late T value = newValue;
   late T oldValue = newValue;

+  @override
+  void initState() {
+    super.initState();
+    _controller = AnimationController(
+      duration: widget.duration,
+      vsync: this,
+    )
+      ..value = 1.0
+      ..addListener(() => setState(
+            () => value = lerp(oldValue, newValue, _animation.value),
+          ));
+
+    _animation = CurvedAnimation(
+      curve: widget.curve,
+      parent: _controller,
+    );
+  }
+
   @override
   void didUpdateWidget(W oldWidget) {
     super.didUpdateWidget(oldWidget);
```

**Comment by halildurmus** [comment] 2022-02-05 17:48
Same here, I started getting this error after upgrading Flutter to `v2.10`.

**Comment by kevinxxq** [comment] 2022-02-11 16:12
Yes. It took place after upgrading Flutter to v2.10.

**Comment by MohamedFBoussaid** [comment] 2022-02-12 18:27
I am getting the same error after updating to Flutter `2.10`

The errors seems to be caused by :
` package:material_floating_search_bar/src/widgets/animation/implicitly_animated_widget.dart`
```

Restarted application in 762ms.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
#1      Element._debugCheckStateIsActiveForAncestorLookup
#2      Element.getElementForInheritedWidgetOfExactType
#3      TickerMode.getNotifier
#4      TickerProviderStateMixin._updateTickerModeNotifier
#5      TickerProviderStateMixin.createTicker
#6      new AnimationController
#7      ImplicitlyAnimatedWidgetState._controller
#8      ImplicitlyAnimatedWidgetState._controller (package:material_floating_search_bar/src/widgets/animation/implicitly_animated_widget.dart)
#9      ImplicitlyAnimatedWidgetState.dispose
#10     StatefulElement.unmount
#11     _InactiveElements._unmount
#12     _InactiveElements._unmount.<anonymous closure>
#13     ComponentElement.visitChildren
#14     _InactiveElements._unmount
#15     _InactiveElements._unmount.<anonymous closure>
#16     ComponentElement.visitChildren
#17     _InactiveElements._unmount
#18     _InactiveElements._unmount.<anonymous closure>
#19     ComponentElement.visitChildren
#20     _InactiveElements._unmount
#21     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#22     _InactiveElements._unmountAll
#23     BuildOwner.lockState
#24     BuildOwner.finalizeTree
#25     WidgetsBinding.drawFrame
#26     RendererBinding._handlePersistentFrameCallback
#27     SchedulerBinding._invokeFrameCallback
#28     SchedulerBinding.handleDrawFrame
#29     SchedulerBinding._handleDrawFrame
#33     _invoke (dart:ui/hooks.dart:151:10)
#34     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#35     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
════════════════════════════════════════════════════════════════════════════════

```

**Comment by devyev** [comment] 2022-02-17 23:18
We are observing the same issue after an upgrade to flutter 2.10. Any timeline on the resolution?

**Comment by oiesc** [comment] 2022-02-22 02:00
Commenting to say that I'm experiencing the same issue.

**Comment by ravipoudel555** [comment] 2022-02-22 05:44
facing the same issue

**Comment by SungilJung** [comment] 2022-02-22 07:54
The issue has been resolved, but has not yet been applied to pub.dev.  You can use [Git dependency](https://docs.flutter.dev/development/packages-and-plugins/using-packages)  temporarily.

**Comment by MrSchmuck** [comment] 2022-02-22 15:37
> The issue has been resolved but has not yet been applied to pub.dev. You can use [Git dependency](https://docs.flutter.dev/development/packages-and-plugins/using-packages) temporarily.

Using the Git dependency has resolved the initial bug but it's created a new one. It seems that you need to tap the search bar twice for the keyboard to pop up. Tested on an emulator and a physical device.

**Comment by bxqm** [comment] 2022-03-05 15:22
Version `0.3.7` is now available that should fix this issue.

**Comment by MohamedFBoussaid** [comment] 2022-03-05 23:36
Thanks @bxqm, I confirm that the issue is fixed with the new release.

**Comment by kevinxxq** [comment] 2022-03-06 02:31
Thank you. It has been fixed.

**Closed** 2022-03-07 14:17 UTC
Labels: bug
